import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { NextUIProvider } from '@nextui-org/system'
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { LayoutHeader } from "./components/header"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  const locales = ["en", "zh"];

  return locales.map((lang) => ({
    lang: lang,
  }))
}

export default async function RootLayout({ children, params: { lang } }) {
  return (
    <html lang={lang}>
      <UserProvider>
        <body>
          <NextUIProvider>
            <NextThemesProvider attribute="class" defaultTheme="dark">
              <LayoutHeader />
              <div className="w-full mx-auto max-w-[1024px] px-6">
                  {children}
              </div>
            </NextThemesProvider>
          </NextUIProvider>
        </body>
      </UserProvider>
    </html>
  );
}
