import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { getSession } from "@auth0/nextjs-auth0";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { lang } }) {
  const session = await getSession();
  const user = session ? session.user : null;
  return (
    <html lang={lang}>
      <UserProvider>
        <body>
          <header className="flex p-8">
            {/* LOGO */}
            <h1><Link href="/">CheckDown</Link></h1>
            {/* gap */}
            <div className="flex-auto"></div>
            {/* user info */}
            {user ? (
              <div className="flex justify-between gap-2">
                <p>{user.nickname}</p>
                <Link href='/me'>my_profile</Link>
                <a href="/api/auth/logout">Logout</a>
              </div>
            ) : (
              <Link href="/api/auth/login">Login</Link>
            )}
          </header>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
