import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { LayoutHeader } from "./components/header"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { lang } }) {
  return (
    <html lang={lang}>
      <UserProvider>
        <body>
          <LayoutHeader />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
