# .github/workflows/doc.yml
name: Document

on:
  workflow_dispatch:

jobs:
  doc:
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      TBLS_DSN: "mysql://${{secrets.DB_USER}}:${{secrets.DB_PASSWORD}}@${{secrets.DB_HOST}}:${{secrets.DB_PORT}}/${{secrets.DB_DATABASE}}"
      TBLS_DOC_PATH: "schema/database"
    steps:
      -
        name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT}}
      -
        uses: k1low/setup-tbls@v1
      -
        name: Run tbls to generate database document
        run: |
          rm -rf $TBLS_DOC_PATH
          tbls doc -t mermaid
      -
        name: Push to wiki
        run: |
          DIFF=$(git diff --name-only)
          echo $DIFF
          if [ "$DIFF" != "" ]
          then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m ":pencil: Update document"
            git push
          fi
