# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - checkdown

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_34eb4dbc3d954bef844ed8a947b26af0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7893fba056ba4deeac6381f186398d57 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_34eb4dbc3d954bef844ed8a947b26af0 }}/checkdown/next:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'checkdown'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3b991f3e97f743d28cfee93b0e8ae4d4 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_34eb4dbc3d954bef844ed8a947b26af0 }}/checkdown/next:${{ github.sha }}'